# Cluster Observability Operator メトリクス収集
---
apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
  name: my-monitoring-stack
  namespace: observability-coo-demo
spec:
  retention: 1d
  namespaceSelector:
    matchNames:
      - observability-coo-demo
  resourceSelector:
    matchLabels:
      my-monitoring-stack: hello-app
  prometheusConfig:
    replicas: 1
  alertmanagerConfig:
    disabled: false
    replicas: 1
---

apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: my-hello-app-service-monitor
  namespace: observability-coo-demo
  labels:
    app.kubernetes.io/part-of: hello-app-monitoring
    my-monitoring-stack: hello-app
spec:
  selector:
    matchLabels:
      app: hello-app
  endpoints:
    - port: management
      path: /metrics
      interval: 15s
  fallbackScrapeProtocol: PrometheusText0.0.4
---

apiVersion: perses.dev/v1alpha2
kind: PersesDatasource
metadata:
  name: my-monitoring-datasource
  namespace: observability-coo-demo
spec:
  config:
    default: true
    display:
      name: My Monitoring Stack Datasource
    plugin:
      kind: PrometheusDatasource
      spec:
        proxy:
          kind: HTTPProxy
          spec:
            url: 'http://my-monitoring-stack-prometheus.observability-coo-demo.svc.cluster.local:9090'

# JBoss EAP 8.1 では /metrics へのアクセス時に空のContent-Typeを出力するため Prometheus が読み込みに失敗する。
# そのため、fallbackScrapeProtocol: PrometheusText0.0.4を設定する必要がある。
# エラーログは prometheus-my-monitoring-stack-0 という Pod に出力される

---
apiVersion: perses.dev/v1alpha2
kind: PersesDashboard
metadata:
  name: my-metrics-dashboard
  namespace: observability-coo-demo
spec:
  config:
    display:
      name: My Metrics Dashboard
    duration: 1h
    layouts:
      - kind: Grid
        spec:
          display:
            title: Application
          items:
            - x: 0
              "y": 0
              width: 12
              height: 6
              content:
                $ref: "#/spec/panels/0_0"
            - x: 12
              "y": 0
              width: 12
              height: 6
              content:
                $ref: "#/spec/panels/0_1"
      - kind: Grid
        spec:
          display:
            title: Java VM Group
            collapse:
              open: true
          items:
            - x: 0
              "y": 6
              width: 12
              height: 6
              content:
                $ref: "#/spec/panels/1_0"
            - x: 12
              "y": 0
              width: 12
              height: 6
              content:
                $ref: "#/spec/panels/1_1"
            - x: 0
              "y": 0
              width: 12
              height: 6
              content:
                $ref: "#/spec/panels/1_2"
          repeatVariable: ""
    panels:
      '1_0':
        kind: Panel
        spec:
          display:
            name: Loaded Class Count
          plugin:
            kind: TimeSeriesChart
            spec: {}
          queries:
            - kind: TimeSeriesQuery
              spec:
                plugin:
                  kind: PrometheusTimeSeriesQuery
                  spec:
                    query: base_classloader_loadedClasses_count
      '0_0':
        kind: Panel
        spec:
          display:
            name: Request Count
          plugin:
            kind: TimeSeriesChart
            spec: {}
          queries:
            - kind: TimeSeriesQuery
              spec:
                plugin:
                  kind: PrometheusTimeSeriesQuery
                  spec:
                    query: jboss_undertow_request_count_total
      '0_1':
        kind: Panel
        spec:
          display:
            name: Session Count
          plugin:
            kind: TimeSeriesChart
            spec: {}
          queries:
            - kind: TimeSeriesQuery
              spec:
                plugin:
                  kind: PrometheusTimeSeriesQuery
                  spec:
                    query: jboss_undertow_active_sessions
      '1_1':
        kind: Panel
        spec:
          display:
            name: Garbage Collection Count
          plugin:
            kind: TimeSeriesChart
            spec: {}
          queries:
            - kind: TimeSeriesQuery
              spec:
                plugin:
                  kind: PrometheusTimeSeriesQuery
                  spec:
                    query: base_gc_total
      '1_2':
        kind: Panel
        spec:
          display:
            name: Garbage Collection Time Total
          plugin:
            kind: TimeSeriesChart
            spec:
              yAxis:
                show: true
                label: ""
                format:
                  unit: seconds
          queries:
            - kind: TimeSeriesQuery
              spec:
                plugin:
                  kind: PrometheusTimeSeriesQuery
                  spec:
                    query: base_gc_time_total_seconds
          links: []
    variables: []
    refreshInterval: 30s
    datasources: {}
